name: verbisense
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  provider: ^6.1.2
  pigment: ^1.0.4
  flutter_svg: ^2.0.14
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  file_picker: ^8.1.4
  firebase_storage: ^12.3.6
  url_launcher: ^6.3.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^2.0.5
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
    # - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
