name: Flutter Clean Arch Build

on:
  push:
    branches:
      - feat/clean-arch


jobs:
    build:
        name: Build Release Apk
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Create .env file
            run: |
              echo "FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}" >> .env
              echo "FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}" >> .env
              echo "FIREBASE_ANDROID_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_ANDROID_MESSAGING_SENDER_ID }}" >> .env
              echo "FIREBASE_ANDROID_PROJECT_ID=${{ secrets.FIREBASE_ANDROID_PROJECT_ID }}" >> .env
              echo "FIREBASE_ANDROID_STORAGE_BUCKET=${{ secrets.FIREBASE_ANDROID_STORAGE_BUCKET }}" >> .env
              echo "FIREBASE_IOS_API_KEY=${{ secrets.FIREBASE_IOS_API_KEY }}" >> .env
              echo "FIREBASE_IOS_APP_ID=${{ secrets.FIREBASE_IOS_APP_ID }}" >> .env
              echo "FIREBASE_IOS_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_IOS_MESSAGING_SENDER_ID }}" >> .env
              echo "FIREBASE_IOS_PROJECT_ID=${{ secrets.FIREBASE_IOS_PROJECT_ID }}" >> .env
              echo "FIREBASE_IOS_STORAGE_BUCKET=${{ secrets.FIREBASE_IOS_STORAGE_BUCKET }}" >> .env
              echo "FIREBASE_IOS_ANDROID_CLIENT_ID=${{ secrets.FIREBASE_IOS_ANDROID_CLIENT_ID }}" >> .env
              echo "FIREBASE_IOS_IOS_CLIENT_ID=${{ secrets.FIREBASE_IOS_IOS_CLIENT_ID }}" >> .env
              echo "FIREBASE_IOS_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_IOS_BUNDLE_ID }}" >> .env

          - name: Setup Flutter
            uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.35.7'
              channel: 'stable'
        
          - name: Install dependencies
            run: flutter pub get
        
          - name: Build Release APK
            run: flutter build apk --release

          - name: Upload Release APK
            uses: actions/upload-artifact@v5
            with:
              name: release-apk
              path: build/app/outputs/flutter-apk/app-release.apk
